name: Cookbooks Upload

on: [ push, workflow_dispatch ]
  
jobs:
  Kitchen-Test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Kitchen Converge
        run: |
          kitchen test
      
  Cookbook-Upload:
    runs-on: self-hosted
    needs: Kitchen-Test
    steps:
      - name: Uploading Cookbooks to Chef Server
        run: |
          rm Berksfile.lock || echo 'Removeal not took place.'
          berks install
          berks upload --force